#!/usr/bin/env bash
#bash script that handles various things
echo "$$" > "/var/run/myscript.pid"
i=1
while [ $i -gt 0 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command";rm "/var/run/myscript.pid";break' 15
	trap 'echo "Y U no love me?!"' 2
	trap 'rm "/var/run/myscript.pid";break' 3
done
