#!/usr/bin/env bash
#bash script to manage the script manage_my_process
if test "${1}" == "start"
then
	echo $$ > "/var/run/my_process.pid"
	echo "manage_my_process started"
	bash manage_my_process
elif test "${1}" == "stop"
then
	pkill -15 -f "$(cat /var/run/my_process.pid)"
	rm "/var/run/my_process.pid"
	echo "manage_my_process stopped"
elif test "${1}" == "restart"
then
	pkill -15 -f "$(cat /var/run/my_process.pid)"
	rm "/var/run/my_process.pid"
	echo "manage_my_process restarted"
	bash manage_my_process
	echo $$ > "/var/run/my_process.pid"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
