#!/usr/bin/env bash
#Bash script that adds enteries to the /etc/hosts file
if grep -q "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*localhost$" /etc/hosts
then
	cp /etc/hosts ~/hosts.new
	sed -i 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*localhost$/127.0.0.2\tlocalhost/g' ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
else
	cp /etc/hosts ~/hosts.new
	echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
fi
if grep -q "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*facebook.com$" /etc/hosts
then
	cp /etc/hosts ~/hosts.new
	sed -i 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*facebook\.com$/8.8.8.8\tfacebook.com/g' ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
else
	cp /etc/hosts ~/hosts.new
	echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
	cp -f ~/hosts.new /etc/hosts
fi
